name: melody
description: "A music player for android"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  audio_service: ^0.18.15
  on_audio_query: ^2.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  tab_container: ^3.5.3
  audio_video_progress_bar: ^2.0.3
  just_audio: ^0.9.42
  flutter_slidable: ^3.1.1
  buttons_tabbar: ^1.3.14
  google_fonts: ^6.2.1
  path: ^1.9.0
  logger: ^2.5.0
  audiotags: ^1.4.1
  ionicons: ^0.2.2
  accordion: ^2.6.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.1
  get_it: ^8.0.2
  audio_session: ^0.1.21
  toastification: ^2.3.0
  flutter_launcher_icons: ^0.14.2
  aligned_dialog: ^0.0.7
  palette_generator: ^0.3.3+5
  marquee: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
